/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { ButtonSize, } from "./components/button/intefaces";
export namespace Components {
    interface VarAnimateBorder {
        "hasBorder": boolean;
    }
    interface VarButton {
        "size": ButtonSize;
    }
    interface VarCard {
    }
    interface VarSidenav {
        "isOpen": boolean;
    }
}
declare global {
    interface HTMLVarAnimateBorderElement extends Components.VarAnimateBorder, HTMLStencilElement {
    }
    var HTMLVarAnimateBorderElement: {
        prototype: HTMLVarAnimateBorderElement;
        new (): HTMLVarAnimateBorderElement;
    };
    interface HTMLVarButtonElement extends Components.VarButton, HTMLStencilElement {
    }
    var HTMLVarButtonElement: {
        prototype: HTMLVarButtonElement;
        new (): HTMLVarButtonElement;
    };
    interface HTMLVarCardElement extends Components.VarCard, HTMLStencilElement {
    }
    var HTMLVarCardElement: {
        prototype: HTMLVarCardElement;
        new (): HTMLVarCardElement;
    };
    interface HTMLVarSidenavElement extends Components.VarSidenav, HTMLStencilElement {
    }
    var HTMLVarSidenavElement: {
        prototype: HTMLVarSidenavElement;
        new (): HTMLVarSidenavElement;
    };
    interface HTMLElementTagNameMap {
        "var-animate-border": HTMLVarAnimateBorderElement;
        "var-button": HTMLVarButtonElement;
        "var-card": HTMLVarCardElement;
        "var-sidenav": HTMLVarSidenavElement;
    }
}
declare namespace LocalJSX {
    interface VarAnimateBorder {
        "hasBorder"?: boolean;
    }
    interface VarButton {
        "size"?: ButtonSize;
    }
    interface VarCard {
    }
    interface VarSidenav {
        "isOpen"?: boolean;
    }
    interface IntrinsicElements {
        "var-animate-border": VarAnimateBorder;
        "var-button": VarButton;
        "var-card": VarCard;
        "var-sidenav": VarSidenav;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "var-animate-border": LocalJSX.VarAnimateBorder & JSXBase.HTMLAttributes<HTMLVarAnimateBorderElement>;
            "var-button": LocalJSX.VarButton & JSXBase.HTMLAttributes<HTMLVarButtonElement>;
            "var-card": LocalJSX.VarCard & JSXBase.HTMLAttributes<HTMLVarCardElement>;
            "var-sidenav": LocalJSX.VarSidenav & JSXBase.HTMLAttributes<HTMLVarSidenavElement>;
        }
    }
}
